mode: demo
symbols: [ULTRACEMCO]
timeframe: 5m
max_position_size: 100000.0
max_loss_per_trade: 1000.0
max_daily_loss: 5000.0
confidence_threshold: 0.72
risk_per_trade_percent: 2.0
kelly_fraction: 0.5
demo_initial_capital: 100000.0
